### ISSUE TITLE
post title should be in quotes?

### ISSUE THREAD

**Issue by miklb** [voxpelli/node-format-microformat#1]
Not sure if I'm using correct terminology, but in my test with Quill, title in the markdown file renders as `title: Item Title`, however it should be `title: "Item Title"`

I'm not exactly sure where the quotes should be inserted, in the `target` var, or in the mapping.

**Comment by voxpelli** [comment]
The Front Matter is generated using the [js-yaml](https://www.npmjs.com/package/js-yaml) module: https://github.com/voxpelli/node-format-microformat/blob/8040c422c355cf576bad6b5b361ad86dc3b2cf1f/index.js#L98

So quotes will be added whenever `js-yaml` considers it to be needed for the YAML to be valid, but will probably – as you're experiencing – be left out when `js-yaml` considers the quote to not be needed for the YAML to be valid.

**Comment by miklb** [comment]
Hmm. wonder if there is a liquid tag to work around that.

**Comment by voxpelli** [comment]
@miklb As it's valid YAML, and as far as I know the Front Matter is just plain YAML that's then parsed by Jekyll, it shouldn't really matter if there's any quotes? So there shouldn't be any need for any workarounds?
