### ISSUE TITLE
Adjust default publish time to be a second or so older than actual time

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/node-format-microformat#4]
If Jekyll is not configured with `future: true` then posts from the future will not be published.

To avoid a mismatch in server times to cause this it could be wise to have the default publish time be a second or so older so that it for sure will be considered a non-future post on the Jekyll build server as well.

I think I have encountered such a scenario on my GitHub Pages blog, where API-created events often weren't published and where the probable cause was that GitHub Pages considered them to be from the future and thus not yet ready to be published.

Thoughts on this change @miklb?

**Comment by miklb** [comment]
I don't see a problem with a few seconds
