### ISSUE TITLE
Configurable file names and paths

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/node-format-microformat#6]
Splitting this up from #5 to keep the discussions around this in one place as it's probably the major change needed to fully support Hugo, the rest of the changes in #5 are fairly minor.

As stated in #5 this is fairly similar to https://github.com/voxpelli/webpage-micropub-to-github/issues/8 and could probably use the same mechanism for both.

@keithjgrant added some comments: https://github.com/voxpelli/node-format-microformat/issues/5#issuecomment-279065943

**Comment by voxpelli** [comment]
@keithjgrant Some feedback:

Regarding the use of `jekyllUtils.generateUrl()` – that's a straight port of the code Jekyll is using to generate a URL, so I'm a bit hesitant to use that for Hugo, but if Hugo doesn't have any slug generation of it's own – then maybe it could be pretty okay to use.

Also: I would probably create a new method that could be used in both `formatFilesFilename()` and `formatFilename()`, that would be given something similar to `permalinkStyle` and then generate an appropriate path and filename. I would then move the default path and filename to just be default values of those new `permalinkStyle` options so that there's only one mechanism for generating them all.

**Comment by voxpelli** [comment]
@keithjgrant I went ahead and added a simple mechanism for filenames, let me know any feedback you might have on it!

**Comment by keithjgrant** [comment]
That looks good. I'm trying to test integration with micropub-to-github... having some troubles though. Possible b/c I'm not too familiar with Heroku

**Comment by keithjgrant** [comment]
I've done some integration testing w/ my site. I added some changes to webpage-micropub-to-github to allow configuration of the filenameStyle (https://github.com/keithjgrant/webpage-micropub-to-github/commits/master), which is in turn passed into this lib as an option.

I now have notes, replies, and likes working, each writing to their own respective directory (with matching permalinks).

Not sure if there's more you have in mind for this ticket, but I think your changes support everything I need for my use case at this point.

**Comment by voxpelli** [comment]
I will consider #7 as well before I close this, then I'll tag a version and update the `micropub-to-github` project

**Comment by keithjgrant** [comment]
As soon as this is tagged, I can submit a PR to webpage-micropub-to-github that has the integration setup (passing the config value into this lib)

(see: commits on https://github.com/keithjgrant/webpage-micropub-to-github/commits/master from Feb 11)

**Comment by voxpelli** [comment]
@keithjgrant Sorry for not having responded! The last two months has for a variety of reasons not seen a lot of time for open source work. I'll try to make a release asap.

**Comment by voxpelli** [comment]
Tagged and released as `0.10.0`, I'll take a look at adding the changes to `webpage-micropub-to-github` now and will follow up on that in https://github.com/voxpelli/webpage-micropub-to-github/issues/18

Closing this issue as fixed. Once again: Sorry for the delay!
